### PR TITLE
Update newTestFile.txt

### PR DESCRIPTION
**Pull request by mdmyr-testUser**
updates something above.

need to create something here.

### CODE REVIEW

**Comment by mdmyr** [comment]
okay updated with your updates.

**Comment by mdmyr** [comment]
We still need to work onthis.

**Comment by mdmyr-testUser** [comment]
> We still need to work onthis.

okay ..what you wanted.

**Comment by mdmyr** [comment]
> > We still need to work onthis.
> 
> okay ..what you wanted.

There is a problem with the file generated we might need to fix that first.

**Comment by mdmyr** [comment]
Anyhow I will go head and merge it but you still need to fix it.

**Pull request closed without merging**
